sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: sgO6VC3Bn9qK+da6p4nF5jj+fYUaDQRUchajKd2GsxRl0zjxljuoxQCYi0lhI2mlcfvNSDt+aF/cYFczECt6pf8vTudXeCEfM1ecAf4UQ5NVgIp71bBZdxrKyVwbe37EYL+IO2KFMnZqH1OR6WS0TW9VOt6Ia8PBsZSvOXQ4C8WCc+uEkFqUdfvkqy3t2CNYGILa8MVQs85WJTe9NFRQqVve67S8ayL4UvYpXHdeYDCgbt7CbhQU7jwIYNmw1B0JsQOWXxE7vJiKsn60fLP7+V3S23jfPI+r2pWW6lCTBrUM7/u06JUoze1SrAAlVjY4c3/tYEfiiUjNvfNphC501Orpaub7u2U74ZTOlUgAMy9MLCKBV28gQfyR5erFBFkSifbHRD6BxXLpmjtC03RIxyBNHPxLkzSz1Bz+oe6rxuS4J6f+M17ZF6e5E3AcI76hpNZgTSHOqnHAZ6IgEiOMLL/070JWBoq40uHaOhDWYvTEHB/hYpiLMnVP00gABb8tvrtQst3woFRFJqQzmu/EMAkMGXgpvPaTpm2FYJCfOPKoLvutVoqZR18IoSKEZ88mLsSco5J1t2NKeczukKMP1po0+lXgkRj/xtqEXAz9HWPDmi2rBXk+qvBeMNT6d4YPV5fk1YoIC3xPEtmPOOEhz+dWoc7MpOFeULVNwrqlOXQ=
  - secure: I48fZzp10VFbXD4pPvjdxSM7VKo9mkrQ2Bu/JP5zSwdRlVEW+vJI/yKC6t5//5gCp/XC0vibaxdmbg73fvJUYvcAGc/yBKChGfR1sjt10kTQYcUwbuVuE4vlStbD3td4vhEZMOL4k0b11tNsuUe43WLJsqdQ3/Znr6sD/+VAlJBUXKUQRGhpAwgw0rpL5U/3wCPbhjmA4SSMUlWjPIPFeWIUcCBEWruk2WjZ3OgYrjcnSw1tQ3LNZgYydaS1XT5MQbU9YeIEmTKWOXJVCTZ8hGYdeubZ10v9KrkFj/lny3m5XiU+Ae+rhV0LJpFuYl1XD897xXrquo4zTSk+Txu95NxfMFdLtt9nfZ+2y+oEUx8qUGxO+dXeg9vtITaa6QL/kWxofmprDurSZqGW+BicSRK7FxShhQZtJ4VKYe2976edIeNOqFtpP9iLOuVKt9LIsuqmbDSDMlC7RnVg33FbEiyOsrXzw/3gYQEyVymiUWUWX8vET6k7O8iz25wufHO4tAIZDG44R4HdCSYXlMHXGHqDQjfYXFxIA88hH1mCk3/EVDjn6ZEqf2nw8r5sUU3CPHXHVv/Ap1UylUvkdLb3GF6MTIdICGE/d5cmbx3T63o0xpDYO1SmeZZ/nIicmdgmK2Ny3hMjTCv33J1Ra3bAv0t2/vJ7/dZU+kgMXfgaXYo=
  - secure: J2J9FF8cT68skHZms+Z7JGRx31jRAhV6B62PC38d3x/Bz8p5c0Oc48mMPeyvY9y/3K4jjm1T34MHKdT2/m06KCvZvBNZQwyptu7BK5C2wnCa1zf4Reh5K5zkQ8zDwU46DFvhEfThDvtvqfgugkMU+4wedYxTl3JXKWpCdZJAMeqtObrtxU89QX6tr1HzpUS3pmUYQbC6/5CLmDnRpzafY6nMpuzhNUxGSPb/8+ZckfkmburoLtpGryOUlVoGGfZkEcDESHATu8N4lJcAXwIQybF1qGoGKs556UfCkfse73yvsV9SW4CzkfmCE2yWG32c0XWiLpRHxTHtBMAStSCa6Xk8QKyxO83agt6a9dkFI1P7mCBjySHmlzRDQ5PmR2z9XlBfrxTapisppmMnvHpLOkqkDljLm8wRSH81fW/3Wjee0UmWNocV72Px9mrN023zPxYLJjSW71CBVPPkou4Pxn7kk/2sPoYN50N+781KRfka6r6nB5/Ygex1r6bstSwWW9U1q6yDxDKJEeFgikiQnn/cPxwAkF2pZRVOlly7MmgS9LbyiSkoW96x68TpG//BCCIzIqJE6WRvqIGHXc6BqVS2gl6k2zcHQN8Z4KExcS9sSuGN7Y5bCqYSJpXEDZ1SMvwCGUWRFj/FX/lxcg2efOK/sMEHXoMnzcv61tEM2zc=
